name: lint and build

on:
  push:
    pull_request:
      types: [opened, reopened, synchronize]

jobs:
  # run clang-format
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file

  # build the application
  build:
    if: steps.lint.output.checks-failed == 0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
